# menu
menu:
  Home: .
  Archives: archives  # 归档
  Categories: categories  # 分类
  Tags: tags  # 标签
  # Repository: repository  # github repositories
#  Books: books  # 豆瓣书单
  Links: links  # 友链
  # About: about  # 关于

# Enable/Disable menu icons
menu_icons:
  enable: true  # 是否启用导航菜单图标
  home: icon-home
  archives: icon-archive
  categories: icon-folder
  tags: icon-tag
  repository: icon-project
  books: icon-book
  links: icon-friend
  about: icon-cup

site:
  favicon: https://avatars.githubusercontent.com/u/15701970
  #manifest:
  site_verification:
#    google:
#    baidu:
#  google_analytics:
#  service_worker:

pagination:
  prev:
    alwayShow: true
  next:
    alwayShow: true

comment:
  type: gitalk  # 启用哪种评论系统
  gitalk: # gitalk. https://gitalk.github.io/
    owner: JoryPein #必须. GitHub repository 所有者，可以是个人或者组织。
    admin: JoryPein #必须. GitHub repository 的所有者和合作者 (对这个 repository 有写权限的用户)。
    repo: Blog #必须. GitHub repository.
    ClientID: 056bdacb76a9e4bcb965 #必须. GitHub Application Client ID.
    ClientSecret: 0ffba4fdf83282c3212dab449113b8da737c7f8e #必须. GitHub Application Client `ecret.
    labels: 'comments'

github:
  username: JoryPein

# wordcount
postCount:
  enable: true
  wordcount: true  # 文章字数统计
  min2read: true  # 阅读时长预计

# 是否开启访问量统计功能(不蒜子)
busuanzi:
  enable: true

search: false # enable local search

toc: true
fancybox: true
# license: 'This article is available under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener noreferrer">Attribution-NonCommercial-ShareAlike 4.0 International (CC BY-NC-SA 4.0)</a> License'
# footer:
#  custom: true

profile:
  enabled: true # Whether to show profile bar
  avatar: https://avatars.githubusercontent.com/u/15701970
  # gravatar: example@example.com # Gravatar email address, if you enable Gravatar, your avatar config will be overriden
  author: Jorymer
  author_title: “ 见诸相非相，即见如来 ”
  author_description: Having fun
  # location: Guangdong China
  follow: https://github.com/jorypein
  # Social Links
  social:
    links:
      github: https://github.com/jorypein
      telegram: https://t.me/jorymer
      # twitter: https://twitter.com/example
      # facebook: /
      # dribbble: /
#      behance: https://www.behance.net/cofess
      rss: atom.xml
    link_tooltip: true # enable the social link tooltip, options: true, false

widgets:
  - board
  - category
  - tag
  - tagcloud
  - archive
  - recent_posts

#widget behaivor
show_count: true

markdown:
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  anchors:
    level: 1
    permalink: false
    separator: '-'
  plugins:
    - '@iktakahiro/markdown-it-katex'
    - markdown-it-emoji

cdn:
  katex: //cdn.jsdelivr.net/npm/katex@0.9.0/dist/katex.min.css
  gitment: //cdn.jsdelivr.net/npm/gitment@0.0.3/style/default.min.css
  gitalk: //cdn.jsdelivr.net/npm/gitalk@1.4.0/dist/gitalk.min.css
  gitalk_js: //cdn.jsdelivr.net/npm/gitalk@1.5.2/dist/gitalk.min.js
  blueimp_md5: //cdn.jsdelivr.net/npm/blueimp-md5@2.10.0/js/md5.min.js
  valine: //cdn.jsdelivr.net/npm/valine@1.3.10/dist/Valine.min.js
  lightgallery_css: //cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/css/lightgallery.min.css
  lightgallery_js: //cdn.jsdelivr.net/npm/lightgallery.js@1.1.3/dist/js/lightgallery.min.js
  aplayer: //cdn.jsdelivr.net/npm/svelte-aplayer/dist/wc/svelte-aplayer.umd.js
